### ISSUE TITLE
Script bin/dev broken

### ISSUE THREAD

**Issue by hww** [excid3/esbuild-rails#14]
In my case `bin/dev` exit, but `rails s` works 

```
21:43:12 js.1   | Done in 0.22s.
21:43:12 web.1  | => Booting Puma
21:43:12 web.1  | => Rails 7.0.4.2 application starting in development
21:43:12 web.1  | => Run `bin/rails server --help` for more startup options
21:43:12 web.1  | Puma starting in single mode...
21:43:12 web.1  | * Puma version: 5.6.5 (ruby 3.2.0-p0) ("Birdie's Version")
21:43:12 web.1  | *  Min threads: 5
21:43:12 web.1  | *  Max threads: 5
21:43:12 web.1  | *  Environment: development
21:43:12 web.1  | *          PID: 332306
21:43:12 web.1  | * Listening on http://127.0.0.1:3000
21:43:12 web.1  | * Listening on http://[::1]:3000
21:43:12 web.1  | Use Ctrl-C to stop
21:43:12 js.1   | exited with code 0
21:43:12 system | sending SIGTERM to all processes
21:43:12 web.1  | - Gracefully stopping, waiting for requests to finish
21:43:12 web.1  | Exiting
21:43:12 web.1  | terminated by SIGTERM
21:43:12 css.1  | exited with code 1
```

**Comment by AndrewCowle** [comment]
@hww I had the same issue setting up a new rails app, after some digging I found that esbuild 0.17.0 (https://yarnpkg.com/package/esbuild) removed the watch command. I just removed the `--watch` options from the profile and I don't get the exit.

**Comment by AndrewCowle** [comment]
@excid3 so this is a replacement file for the esbuild.conifg file I currently have in the project? My esbuild.config.js currently contains

`const path = require('path')
const rails = require('esbuild-rails')

require("esbuild").build({
    entryPoints: ["application.js"],
    bundle: true,
    outdir: path.join(process.cwd(), "app/assets/builds"),
    absWorkingDir: path.join(process.cwd(), "app/javascript"),
    plugins: [rails()],
}).catch(() => process.exit(1))`
