### ISSUE TITLE
Request to Upgrade the glob Package Dependency from Version 9 to Version 10

### ISSUE THREAD

**Issue by navidemad** [excid3/esbuild-rails#17]
Firstly, I would like to express my appreciation for your work on esbuild-rails and for the rails community.

While working with this package, we noticed that it currently uses version 9 of the glob package as a dependency.
However, we are maintaining two versions of glob in our project due to this, as other packages we use have been already upgraded to version 10.

The [changelog for glob](https://github.com/isaacs/node-glob/blob/main/changelog.md) shows several enhancements and adjustments in version 10, considering these points, would it be possible to upgrade the glob dependency in esbuild-rails to version 10? This would greatly simplify our dependency management and potentially provide the benefits of the changes made in glob version 10.

I understand that such an upgrade could involve a significant amount of work, especially if it necessitates changes in the existing codebase of esbuild-rails. I would be happy to contribute if necessary, or assist in any way I can.

Looking forward to your thoughts on this.

```yaml
/glob@10.2.6:
  resolution: {integrity: sha512-U/rnDpXJGF414QQQZv5uVsabTVxMSwzS5CH0p3DRCIV6ownl4f7PzGnkGmvlum2wB+9RlJWJZ6ACU1INnBqiPA==}
  engines: {node: '>=16 || 14 >=14.17'}
  hasBin: true
  dependencies:
    foreground-child: 3.1.1
    jackspeak: 2.2.1
    minimatch: 9.0.1
    minipass: 6.0.2
    path-scurry: 1.9.2
  dev: false

/glob@9.3.5:
  resolution: {integrity: sha512-e1LleDykUz2Iu+MTYdkSsuWX8lvAjAcs0Xef0lNIu0S2wOAzuTxCJtcd9S3cijlwYF18EsU3rzb8jPVobxDh9Q==}
  engines: {node: '>=16 || 14 >=14.17'}
  dependencies:
    fs.realpath: 1.0.0
    minimatch: 8.0.4
    minipass: 4.2.8
    path-scurry: 1.9.2
  dev: false
    
/esbuild-rails@1.0.4(esbuild@0.17.19):
    resolution: {integrity: sha512-UZXrKGYKzViZqse1fawR5RP+1QxD9npFafANm6K3ftJjN8RhCnDhRpnL+3xWtfV+QQkjs6mOZmWmAwX5KAkQxA==}
    peerDependencies:
      esbuild: '*'
    dependencies:
      esbuild: 0.17.19
      glob: 9.3.5
    dev: false
```

**Comment by wrmk** [comment]
Hi, I like to mention that glob^10 in some cases causes a [problem](https://github.com/eslint/eslint/discussions/17215) with the "strip-ansi" dependency.
I faced this problem and had to use the "1.0.4" version.

**Comment by t27duck** [comment]
I opened an issue explaining it in more detail along with a workaround

https://github.com/excid3/esbuild-rails/issues/18
