### ISSUE TITLE
Upgrading to 1.0.5 breaks yarn install due to glob 10 sub-dependencies

### ISSUE THREAD

**Issue by t27duck** [excid3/esbuild-rails#18]
Simple example:

package.json:

```json
{
  "name": "app",
  "private": "true",
  "dependencies": {
    "@hotwired/stimulus": "^3.2.1",
    "esbuild": "^0.17.19",
    "esbuild-rails": "^1.0.4"
  }
}
```

Your local version of yarn must not have installed glob 10 before

```bash
$ yarn cache clean
```

Install the packages

```bash
$ yarn install
yarn install v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 27.76s.
```

Update `esbuilt-rails` to 1.0.5 in `package.json` and try to install the package with the updated glob 10.0 dependency.

```bash
$ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["strip-ansi@^6.0.1"] is trying to unpack in the same destination "/home/tony/.cache/yarn/v6/npm-strip-ansi-cjs-6.0.1-9e26c63d30f53443e9489495b2105d37b67a85d9-integrity/node_modules/strip-ansi-cjs" as pattern ["strip-ansi-cjs@npm:strip-ansi@^6.0.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.1.0"] is trying to unpack in the same destination "/home/tony/.cache/yarn/v6/npm-string-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["strip-ansi@^6.0.0"] is trying to unpack in the same destination "/home/tony/.cache/yarn/v6/npm-strip-ansi-cjs-6.0.1-9e26c63d30f53443e9489495b2105d37b67a85d9-integrity/node_modules/strip-ansi-cjs" as pattern ["strip-ansi-cjs@npm:strip-ansi@^6.0.1"]. This could result in non-deterministic behavior, skipping.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.47s.
```

Even though this is a "warning", yarn does not install the sub dependency and so everything breaks because JS is looking for code in a package that is not installed.

Digging through the lock file, `glob` 10 depends on `jackspeak`. The latest `jackspeak` uses a fork of the `cliui` package called `@isaacs/cliui` which has this... odd syntax for its dependencies. 

```
"@isaacs/cliui@^8.0.2":
  version "8.0.2"
  resolved "https://registry.yarnpkg.com/@isaacs/cliui/-/cliui-8.0.2.tgz#b37667b7bc181c168782259bab42474fbf52b550"
  integrity sha512-O8jcjabXaleOG9DQ0+ARXWZBTfnP4WNAqzuiJK7ll44AmxGKv/J2M4TPjxjY3znBCfvBXFzucm1twdyFybFqEA==
  dependencies:
    string-width "^5.1.2"
    string-width-cjs "npm:string-width@^4.2.0"
    strip-ansi "^7.0.1"
    strip-ansi-cjs "npm:strip-ansi@^6.0.1"
    wrap-ansi "^8.1.0"
    wrap-ansi-cjs "npm:wrap-ansi@^7.0.0"
```

Workaround:

Set `jackspeak` to version 2.0.3 in `package.json` and things seem to work again.

```
  "resolutions": {
    "jackspeak": "2.0.3"
  }
```

Possible options:

- Go back to the old glob dependency.
- Switch to an alternative like [fast-glob](https://www.npmjs.com/package/fast-glob)

Apparently, for errors like this, the solution according to yarn issues is to "upgrade to yarn 2" which currently isn't a solution for Rails as it assumes yarn 1...

**Comment by excid3** [comment]
JavaScript is awful. 🙃

I don't like having to specifically use an older version of glob, so maybe we look into fast-glob?

**Comment by excid3** [comment]
Saw this one as well that has 0 dependencies which might be nice. https://github.com/thecodrr/fdir

**Comment by excid3** [comment]
I can't seem to reproduce your issue:

<img width="456" alt="Screenshot 2023-06-01 at 6 46 34 PM" src="https://github.com/excid3/esbuild-rails/assets/67093/e43200dd-ccce-4a18-87d3-9c0bc6c163bb">

**Comment by t27duck** [comment]
I'm able to still reproduce in WSL2, macOS, and in two dependabot failed CI runs.

I noticed your first `yarn install` didn't mention it couldn't find a lock file. Was there one in the directory you were in or an existing `node_modules` folder?

Output from the Github Actions for updating this package:

![image](https://github.com/excid3/esbuild-rails/assets/545604/db6bbc74-14d4-4d9a-88fa-156296966078)

**Comment by excid3** [comment]
I deleted both, redid the steps and it still worked fine for some reason. 🙃

Have you had a chance to test out the fast-glob version and confirm it works?

**Comment by t27duck** [comment]
So I made a public repo trying to reproduce in github actions. Even though I said "^1.0.4" in `package.json` yarn decided it wanted 1.0.5. I set up a quick Github action to just run yarn install.

While the `yarn install` step did "work", it still threw the warnings and refused to install all the packages.

https://github.com/t27duck/esbuild_test/actions/runs/5150487055/jobs/9274676473
