### ISSUE TITLE
global jquery

### ISSUE THREAD

**Issue by kivanio** [excid3/esbuild-rails#4]
Is there a way to expose a global jQuery using this?

**Comment by excid3** [comment]
@leoplct your code `window.$` AFTER you tried to use it, which won't work of course. Assign the window variable before you do anything else.

**Comment by excid3** [comment]
jQuery UI is super old and doesn't support ESM. 

You can do it by importing jQuery in a separate file:

```bash
yarn add jquery jquery-ui
```

```javascript
// app/javascript/jquery.js
import jquery from 'jquery';
window.jQuery = jquery;
window.$ = jquery;
```

```javascript
//app/javascript/application.js
import "./jquery"
import "jquery-ui/jquery-ui"

$(function() {
  $(".datepicker").datepicker();
});
```

**Comment by excid3** [comment]
Confirmed that a custom jquery-ui build does work. 

I dropped jquery-ui build into the src folder and imported that after the jquery file and everything functions.

<img width="1454" alt="Screen Shot 2021-10-15 at 4 48 16 PM" src="https://user-images.githubusercontent.com/67093/137557196-afab6f9f-18c5-42ca-aa85-e23f64bb33ff.png">
<img width="1456" alt="Screen Shot 2021-10-15 at 4 48 51 PM" src="https://user-images.githubusercontent.com/67093/137557225-9d9ee897-a6c6-40cd-b3c9-d8886fda0088.png">

**Comment by kivanio** [comment]
@excid3 You are the BEST! 
Thank you ❤️

**Comment by bfcoder** [comment]
@excid3 Did you figure out the ui icons image loading for jquery-ui?
![2022-07-11 18_02_08-Window](https://user-images.githubusercontent.com/1216167/178379019-688ace36-4016-444c-ae88-7812d8e369a1.jpg)

**Comment by bfcoder** [comment]
I solved it by using the downloaded code for javascript. And the NPM package for CSS. Dumb, but it works. Maybe one day someone will fix the NPM package javascript to support ESM.

**Comment by excid3** [comment]
That's cool @KonnorRogers! TIL 💪

**Comment by KonnorRogers** [comment]
@excid3 i haven't used it yet, but this is how injecting React into every file without needing to import it works.

**Comment by excid3** [comment]
Untested code is best code (right?)

**Comment by adilmahmoodc** [comment]
@kivanio @excid3 
If I reload the page, it is working fine, but if I come to page from any link, due to turbo stimulus controllers give undefined $(...).
