### ISSUE TITLE
Production/Heroku issues?

### ISSUE THREAD

**Issue by joemasilotti** [excid3/esbuild-rails#8]
Is there any additional configuration needed to get this working in production on Heroku? Everything works fine locally but when deployed there are no CSS or JavaScript assets.

---

P.S. Thanks so much for this – being able to glob import Stimulus controllers is 🔥

**Comment by excid3** [comment]
This is an esbuild plugin, so it runs when `yarn build` runs. If that's not happening, that's an issue with your jsbundling-rails setup. 

That package will run `yarn build` during asset compilation, so you might check the jsbundling-rails issues for some information on that. 👍 

For example: https://github.com/rails/jsbundling-rails/issues/16

**Comment by joemasilotti** [comment]
Turns out this isn't directly related to esbuild-rails, but rather jsbundling-rails. From the [README](https://github.com/rails/jsbundling-rails#why-does-esbuild-overwrite-my-applicationcss):

> If you [import CSS](https://esbuild.github.io/content-types/#css-from-js) in your application.js while using esbuild, you'll be creating both an app/assets/builds/application.js and app/assets/builds/application.css file when bundling. The latter can conflict with the app/assets/builds/application.css produced by [cssbundling-rails](https://github.com/rails/cssbundling-rails)[](https://github.com/excid3/esbuild-rails/issues/8#license). The solution is to either change the output file for esbuild (and the references for that) or for cssbundling. Both are specified in package.json.

`application.js` was importing some library-specific CSS – removing that import fixed everything. I'm not sure how to apply the required changes mentioned above, but I'll post here when I do.

**Comment by excid3** [comment]
My recommendation is don't include any CSS in your JS files if you're going to use esbuild. Leave all the CSS imports in your CSS files.

**Comment by joemasilotti** [comment]
That did the trick! Thanks for helping debug, Chris.

To summarize, importing _any_ CSS in `application.js` caused esbuild to overwrite `application.css` with _only_ the CSS imported in JavaScript. Hence, clobbering my styles. The solution was to move the CSS import to `application.css` (`application.tailwind.css` in my case).
