### ISSUE TITLE
Can it write out which file(s) were built?

### ISSUE THREAD

**Issue by silent-e** [excid3/esbuild-rails#9]
I don't know if this is related to `esbuild` or `esbuild-rails` but, when I'm running my `bin/dev` script, the result of my javascript compilation isn't being output.  Each time the sass plugin compiles a file it shows up in my Foreman output.

I'd love it if the javascript compilation process did that too.  My config file is the same as in the README, except for the entry points.

Is this something that can be done?

(e)

**Comment by excid3** [comment]
This would be more of a question for `esbuild` but you might want to set the `logLevel` for esbuild. For example, `logLevel: 'info'`

**Comment by silent-e** [comment]
That did it.  Now the watch process is telling me when a build started, which file, and when the build finished.  Exactly what I wanted.

Thanks much!
